basePath: /
host: localhost:8080
info:
  contact:
    email: arkisewdemisew84@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for Project-1.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Project-1 API
  version: "1.0"
paths: {}
swagger: "2.0"
